debug: false

number-format:
  locale: en-US
  int-format: '#,###'
  double-format: '#,##0.##'
  short-number-format:
    format: '#,##0.##'
    suffixes:
      thousand: "K"
      million: "M"
      billion: "B"
      trillion: "T"
      quadrillion: "Q"

user-auto-save-in-minutes: 30
# Can be yaml or mysql
storage-type: "yaml"

mysql:
  host: "127.0.0.1"
  port: "3306"
  ssl: false
  database: "db name"
  username: "username"
  password: "password"
  network-latency: 500
  pool-size: 10
  sync-retry-count: 3

# Tracks blocks placed by players
block-tracker:
  enabled: true
  # can be file or sqlite
  storage-type: "file"

config-version: 2