debug: false

number-format:
  locale: en-US
  int-format: '#,###'
  double-format: '#,##0.##'
  short-number-format:
    format: '#,##0.##'
    suffixes:
      thousand: "K"
      million: "M"
      billion: "B"
      trillion: "T"
      quadrillion: "Q"

user-auto-save-in-minutes: 10
# Can be yaml or mysql
# If you use mysql, your leaderboard data will be stored in mysql as well
# otherwise, it will be stored in a local sqlite database
storage-type: "yaml"

mysql:
  host: "127.0.0.1"
  port: 3306
  ssl: false
  database: "db name"
  username: "username"
  password: "password"
  network-latency: 500
  pool-size: 10
  sync-retry-count: 3

# Tracks blocks placed by players
block-tracker:
  enabled: true
  # can be file or sqlite
  storage-type: "sqlite"

leaderboards:
  empty-placeholder: "---"

config-version: 3