name: AuroraLib
version: '${version}'
main: gg.auroramc.auroralib.AuroraLib
api-version: 1.19
authors: ["Perwollnt", "erik_sz"]
softdepend:
  - PlaceholderAPI
libraries:
  - net.kyori:adventure-text-minimessage:4.17.0
  - net.kyori:adventure-text-serializer-plain:4.17.0
  - net.kyori:adventure-text-serializer-legacy:4.17.0
  - net.kyori:adventure-api:4.17.0
  - net.kyori:adventure-platform-bukkit:4.3.2
