name: Aurora
version: '${version}'
main: gg.auroramc.aurora.Aurora
api-version: 1.19
authors: [ "erik_sz" ]
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Vault
  - WorldGuard
  - CMI
  - Essentials
  - Multiverse-Core
  - WildRegeneration