name: Aurora
version: '${version}'
main: gg.auroramc.aurora.Aurora
api-version: 1.19
authors: [ "erik_sz" ]
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Vault
  - WorldGuard
  - CMI
  - Essentials
  - Multiverse-Core
  - WildRegeneration

permissions:
  aurora.core.admin:
    description: Allows the player to use all AuroraAPI commands
    default: op

commands:
  aurora:
    permission: aurora.core.admin
