CREATE TABLE IF NOT EXISTS `%user_table%` (
  player_uuid VARCHAR(36) NOT NULL PRIMARY KEY,
  data MEDIUMTEXT
) CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `%sync_table%` (
    player_uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8;