name: Upload Artifacts and Notify Discord

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aurora
          path: build/libs/Aurora-**.jar

      - name: Get commit messages since last push
        id: commits
        run: |
          echo "Fetching commits between ${{ github.event.before }} and ${{ github.sha }}"
          commits=$(git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:"- %s")
          echo "COMMITS=$commits" >> $GITHUB_ENV

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMITS: ${{ env.COMMITS }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "Sending commit messages to Discord"
          payload=$(jq -n --arg commits "$COMMITS" --arg repo "$GITHUB_REPOSITORY" --arg sha "$GITHUB_SHA" '{
            "embeds": [
              {
                "title": "New Dev Build for \($repo)",
                "description": "New dev build available. Latest commits:\n\($commits)",
                "url": "https://github.com/\($repo)/commit/\($sha)",
                "color": 15258703
              }
            ]
          }')
          curl -X POST -H "Content-Type: application/json" -d "$payload" $DISCORD_WEBHOOK_URL